language: node_js
node_js:
  - '7'
branches:
  only: master
env:
  - EXTENSION_ID=kbbbjimdjbjclaebffknlabpogocablj
deploy:
  provider: script
  skip_cleanup: true
  script: npm run update-version; npm run release-cws; npm run release-amo
  on:
      branch: master
