language: node_js
node_js:
  - 'node'
env:
  - EXTENSION_ID=kbbbjimdjbjclaebffknlabpogocablj
deploy:
  provider: script
  skip_cleanup: true
  script: npm run update-version; npm run release
  on:
      branch: master
